<?php

$cfg->postTags = [
    'gold' => [
        'name' => _('Gold'),
        'display' => '<span class="tag text goldaccount">[NAME]</span>',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Have a Gold account'),
    ],
    'platinum' => [
        'name' => _('Platinum'),
        'display' => '<img class="tag platinum" src="' . $cfg->staticUrl . '/img/tags/platinum.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => false,
        'description' => _('Have a permanent Gold account'),
    ],
    'king_of_ylilauta' => [
        'name' => _('The King of Ylilauta'),
        'display' => '<img class="tag king" src="' . $cfg->staticUrl . '/img/tags/king.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => false,
        'description' => _('Have a maximum level platinum account'),
    ],
    'bier' => [
        'name' => _('Bier'),
        'display' => '<img class="tag bier" src="' . $cfg->staticUrl . '/img/tags/bier.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Have spent a total of 10€ on any Ylilauta items to help the admins to relieve their work stresi wories'),
    ],

    'unique_snowflake' => [
        'name' => _('Unique snowflake'),
        'display' => '<img class="tag snowflake" src="' . $cfg->staticUrl . '/img/tags/snowflake.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Be a unique snowflake'),
    ],

    'epic_guy' => [
        'name' => _('Epic guy'),
        'display' => '<img class="tag epicguy" src="' . $cfg->staticUrl . '/img/tags/epicguy.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Epic threads give epic tags - have an archived thread'),
    ],
    'advent_burger' => [
        'name' => _('Adventburger'),
        'display' => '<img class="tag adventburger" src="' . $cfg->staticUrl . '/img/tags/adventburger.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Get your thread to the advent calendar of Ylilauta'),
    ],

    'midsummer_beer' => [
        'name' => _('Midsummer beer'),
        'display' => '<img class="tag beer" src="' . $cfg->staticUrl . '/img/tags/beer.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Submit a post during midsummer'),
    ],

    'hyperactive' => [
        'name' => _('Hyperactive'),
        'display' => '<img class="tag hyperactive" src="' . $cfg->staticUrl . '/img/tags/hyperactive.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Have at least 100 000 activity points'),
    ],
    'top_commenter' => [
        'name' => _('Top commenter'),
        'display' => '<img class="tag topcommenter" src="' . $cfg->staticUrl . '/img/tags/topcommenter.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Your posts have received at least 1000 upboats'),
    ],
    'upboat_pro' => [
        'name' => _('Upboated :D'),
        'display' => '<img class="tag upboat" src="' . $cfg->staticUrl . '/img/tags/upboat.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Given at least 1000 upboats'),
    ],
    'gold_commenter' => [
        'name' => _('Gold commenter'),
        'display' => '<img class="tag topcommenter" src="' . $cfg->staticUrl . '/img/tags/goldcommenter.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('You have received a Gold account from any of your posts'),
    ],
    'goldboated' => [
        'name' => _('Goldboated :D'),
        'display' => '<img class="tag goldboat" src="' . $cfg->staticUrl . '/img/tags/goldboat.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Donated a Gold account to another user'),
    ],
    'yolo_pro' => [
        'name' => _('YOLO-pro'),
        'display' => '<img class="tag yolopro" src="' . $cfg->staticUrl . '/img/tags/yolopro.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => false,
        'description' => _('Have achieved a YOLO-jackpot'),
    ],

    'assburger' => [
        'name' => _('Assburger'),
        'display' => '<img class="tag assburger" src="' . $cfg->staticUrl . '/img/tags/assburger.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('You need to figure out how to find this'),
    ],
    'grill' => [
        'name' => _('BTW I\'m a grill'),
        'display' => '<img class="tag grill" src="' . $cfg->staticUrl . '/img/tags/grill.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('You need to figure out how to find this'),
    ],
    'anonymous_burger' => [
        'name' => _('Anonymous is a leguan'),
        'display' => '<img class="tag anonymousburger" src="' . $cfg->staticUrl . '/img/tags/anonymousburger.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('There might be a few ways to obtain this - someday, somewhere...'),
    ],

    'seal_of_ylilauta' => [
        'name' => _('Seal of Ylilauta'),
        'display' => '<img class="tag sealofylilauta" src="' . $cfg->staticUrl . '/img/tags/sealofylilauta.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('You have done something good for Ylilauta, like reported a bug or given a good development idea'),
    ],
    'ylilauta_pro' => [
        'name' => _('Ylilauta-pro'),
        'display' => '<img class="tag ylilautapro" src="' . $cfg->staticUrl . '/img/tags/ylilautapro.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Have an user account older than a year'),
    ],
    'always_been_here' => [
        'name' => _('Always been here'),
        'display' => '<img class="tag alwaysbeenhere" src="' . $cfg->staticUrl . '/img/tags/alwaysbeenhere.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Have an user account older than 3 years'),
    ],
    'wizard' => [
        'name' => _('What the heck am I still doing here!?'),
        'display' => '<img class="tag wizard" src="' . $cfg->staticUrl . '/img/tags/wizard.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Have an user account older than 6 years'),
    ],

    'markoboy' => [
        'name' => _('Markoboy'),
        'display' => '<img class="tag markoboy" src="' . $cfg->staticUrl . '/img/tags/markotag.png" alt="" title="13.9.2014 Never Forget!" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('Took part in the markoboy87 -fundraiser (September 2014)'),
    ],
    'niilo22' => [
        'name' => _('niilo22'),
        'display' => '<img class="tag niilo22_1" src="' . $cfg->staticUrl . '/img/tags/niilo22_1.png" alt="" title="6.10.2015 Never Forget!" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('Took part in the niilo22 -fundraiser (October 2015)'),
    ],
    'niilo22_ultimate' => [
        'name' => _('niilo22 Ultimate'),
        'display' => '<img class="tag niilo22_2" src="' . $cfg->staticUrl . '/img/tags/niilo22_2.png" alt="" title="6.10.2015 Never Forget!" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('Took part in the niilo22 -fundraiser with a sum more than the average payment (October 2015)'),
    ],
    'transporter' => [
        'name' => _('Transporter'),
        'display' => '<img class="tag transporter" src="' . $cfg->staticUrl . '/img/tags/transporter.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('Took part in the Ylis Roadtrip -fundraiser (August 2016)'),
    ],
    'transporter_flames' => [
        'name' => _('Transporter with flames'),
        'display' => '<img class="tag transporter_flames" src="' . $cfg->staticUrl . '/img/tags/transporter_flames.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('Took part in the Ylis Roadtrip -fundraiser with a sum of 25€ or more (August 2016)'),
    ],
    'invalid' => [
        'name' => _('Invalid'),
        'display' => '<img class="tag invalid" src="' . $cfg->staticUrl . '/img/tags/invalid.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('Took part in the Ylis gives back! -fundraiser (June 2017)'),
    ],
    'honorary_burger' => [
        'name' => _('Honorary burger'),
        'display' => '<img class="tag honoraryburger" src="' . $cfg->staticUrl . '/img/tags/honoraryburger.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('Took part in the Ylis gives back! -fundraiser with a sum of more than the average (June 2017)'),
    ],
    'help_helper' => [
        'name' => _('Help Helper'),
        'display' => '<img class="tag help_helper" src="' . $cfg->staticUrl . '/img/tags/help_helper.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('Took part in the Food Help Helping -fundraiser (December 2018)'),
    ],
    'good_apulitan' => [
        'name' => _('Good Apulitan'),
        'display' => '<img class="tag good_apulitan" src="' . $cfg->staticUrl . '/img/tags/good_apulitan.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('Took part in the Food Help Helping -fundraiser with a sum of more than the average (December 2018)'),
    ],
    'macaroni' => [
        'name' => _('Macaroni'),
        'display' => '<img class="tag macaroni" src="' . $cfg->staticUrl . '/img/tags/macaroni.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('All of my money went to Hursti, now I will have to eat macaroni'),
    ],

    'corona' => [
        'name' => _('Coronavirus'),
        'display' => '<img class="tag corona" src="' . $cfg->staticUrl . '/img/tags/corona.png" alt="" title="[NAME]" />',
        'obtainable' => true,
        'listed' => true,
        'description' => _('Got infected by a virtual coronavirus'),
    ],

    'christmas_burger' => [
        'name' => _('Christmasburger'),
        'display' => '<img class="tag christmasburger" src="' . $cfg->staticUrl . '/img/tags/christmasburger.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('Purchased a Gold account during december of 2015'),
    ],
    'finland' => [
        'name' => _('Finland 100 years'),
        'display' => '<img class="tag finlandtag" src="' . $cfg->staticUrl . '/img/tags/finland.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('Purchased a Gold account on Finland\'s 100th independence day'),
    ],
    'server_flames' => [
        'name' => _('Mass storage massacre'),
        'display' => '<img class="tag server_flames" src="' . $cfg->staticUrl . '/img/tags/server_flames.png" alt="" title="[NAME]" />',
        'obtainable' => false,
        'listed' => true,
        'description' => _('Lived to tell the tales of the great Mass storage massacre (June 2017)'),
    ],
];
